### ISSUE TITLE
Splashforce carts error

### ISSUE THREAD

**Issue by saigorupati** [fraserdale/freeCarts#52]
Getting this error when I try to use it with splashforce.

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.splashforceCartProperties (/Users/saigorupati/Desktop/freeCarts-master/adapters.js:4:30)
    at message.embeds.forEach.e (/Users/saigorupati/Desktop/freeCarts-master/main.js:131:79)
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (/Users/saigorupati/Desktop/freeCarts-master/main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (/Users/saigorupati/Desktop/freeCarts-master/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/Users/saigorupati/Desktop/freeCarts-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/Users/saigorupati/Desktop/freeCarts-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/Users/saigorupati/Desktop/freeCarts-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/Users/saigorupati/Desktop/freeCarts-master/node_modules/ws/lib/event-target.js:120:16)

**Comment by saigorupati** [comment]
came up with a quick fix but its not as clean

module.exports.splashforceCartProperties = (e, cartNum) => {
	const email = e.fields[0]['value'];
	const pass = e.fields[1]['value'];
	const loginURL = e.url;
	const img = e.thumbnail.url;
	const size = e.fields[3]['value'];

	return new CartProperties(cartNum, email, pass, loginURL, img, size);
}

**Comment by fraserdale** [comment]
Yeah, implementing today
