### ISSUE TITLE
SoleAIO cart error 

### ISSUE THREAD

**Issue by OneLifeOnly** [fraserdale/freeCarts#53]
ReferenceError: footerText is not defined
    at Object.module.exports.getBotByFooter.footer [as getBotByFooter] (C:\Users                 \Kevin\Desktop\freeCarts\utils.js:28:7)
    at message.embeds.forEach.e (C:\Users\Kevin\Desktop\freeCarts\main.js:129:47                 )
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (C:\Users\Kevin\Desktop\freeCarts\main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Kevin\Desktop\freeCarts\node_module                 s\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Kevin\Desktop\freeCarts\node_modu                 les\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Kevin\Desktop\freeCarts\node_modul                 es\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modu                 les\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\ws\lib                 \event-target.js:120:16)

**Comment by SneakyFish5** [comment]
Do you have an example or a picture of the webhook sent by Sole? Maybe the footer text was changed?

**Comment by OneLifeOnly** [comment]
![solesolesole](https://user-images.githubusercontent.com/25411506/59398523-889ddc80-8d5e-11e9-9e20-9226247795c4.png)

**Comment by ShaneAbara** [comment]
When I edited the footer, I ended up getting this error.

TypeError: Cannot read property 'value' of undefined
    at Object.module.exports.soleaioCartProperties

**Comment by SneakyFish5** [comment]
Was there more to the error or just that?

**Comment by OneLifeOnly** [comment]
> Was there more to the error or just that?

ReferenceError: footerText is not defined
    at Object.module.exports.getBotByFooter.footer [as getBotByFooter] (C:\Users          \Kevin\Desktop\freeCarts\utils.js:28:7)
    at message.embeds.forEach.e (C:\Users\Kevin\Desktop\freeCarts\main.js:129:47          )
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (C:\Users\Kevin\Desktop\freeCarts\main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Kevin\Desktop\freeCarts\node_module          s\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Kevin\Desktop\freeCarts\node_modu          les\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Kevin\Desktop\freeCarts\node_modul          es\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modu          les\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\ws\lib          \event-target.js:120:16)

**Comment by SneakyFish5** [comment]
I meant to ask @ShaneAbara

**Comment by OneLifeOnly** [comment]
Getting following error message on latest update

TypeError: Cannot read property 'value' of undefined
    at Object.module.exports.soleaioCartProperties (C:\Users\Kevin\Desktop\freeCarts\adapters.js:48:30)
    at message.embeds.forEach.e (C:\Users\Kevin\Desktop\freeCarts\main.js:131:79)
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (C:\Users\Kevin\Desktop\freeCarts\main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\ws\lib\event-target.js:120:16)
