### ISSUE TITLE
Soleaio error

### ISSUE THREAD

**Issue by OneLifeOnly** [fraserdale/freeCarts#55]
on  latest update getting the following error

TypeError: Cannot read property 'value' of undefined
    at Object.module.exports.soleaioCartProperties (C:\Users\Kevin\Desktop\freeCarts\adapters.js:48:30)
    at message.embeds.forEach.e (C:\Users\Kevin\Desktop\freeCarts\main.js:131:79)
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (C:\Users\Kevin\Desktop\freeCarts\main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\ws\lib\event-target.js:120:16)

**Comment by fraserdale** [comment]
Fixed. 
https://github.com/fraserdale/freeCarts/commit/626fc615bc533bc3de421b335f0211be4f1977d5
