### ISSUE TITLE
KodaiAIO error

### ISSUE THREAD

**Issue by OneLifeOnly** [fraserdale/freeCarts#56]
ReferenceError: footerText is not defined
    at Object.module.exports.getBotByFooter.footer [as getBotByFooter] (C:\Users\Kevin\Desktop\freeCarts\utils.js:28:7)
    at message.embeds.forEach.e (C:\Users\Kevin\Desktop\freeCarts\main.js:129:47)
    at Array.forEach (<anonymous>)
    at Client.bot.on.message (C:\Users\Kevin\Desktop\freeCarts\main.js:127:32)
    at Client.emit (events.js:182:13)
    at MessageCreateHandler.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Kevin\Desktop\freeCarts\node_modules\ws\lib\event-target.js:120:16)

**Comment by fraserdale** [comment]
Duplicate fixed https://github.com/fraserdale/freeCarts/commit/1cca760ae3143d24bca4e59a35611fc281c8ac60
