### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by MarcoD1337** [fraserdale/freeCarts#59]
```C:\Users\marco\Desktop\Cooking Tools\freeCarts>node main
C:\Users\marco\Desktop\Cooking Tools\freeCarts\main.js:25
app.on('ready', function () {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\Users\marco\Desktop\Cooking Tools\freeCarts\main.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)```

**Comment by SneakyFish5** [comment]
Did you do `npm i`?

**Comment by MarcoD1337** [comment]
yea
